# Spring Boot configuration
spring:
  profiles:
    active: google
# Spring Security configuration
security:
  oauth2:
    client:
      clientId: 674426920954-1o67sokjtqlj3blr7akni6mbsc3qqr75.apps.googleusercontent.com
      clientSecret: V3UwEC0XmI9f_-tNDcRPOxGb
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
